### ISSUE TITLE
Toolbar content margins are irregular

### ISSUE THREAD

**Issue by marcellogalhardo** [whitescent/Mastify#103]
The toolbar content margins from the Home and Explore tabs are irregular. When you press between them, the avatar clearly changes position.

Both Notifications and Explore tabs seem to match.

It would be great if all tabs could match the position of their content elements.

![Screenshot_20240329-011913.png](https://github.com/whitescent/Mastify/assets/4348197/3da0bd9e-4024-4b5d-af50-947b0332f05c)

![Screenshot_20240329-011935.png](https://github.com/whitescent/Mastify/assets/4348197/0915ebbd-c3ae-4c66-83ee-5476b6709f94)

**Comment by whitescent** [comment]
fixed https://github.com/whitescent/Mastify/commit/4a2b288e0baa2582547242a3f25bce1a8a9253e2

It will be fixed in the next version (1.4.25-alpha)
