### ISSUE TITLE
Menu drawer button (photo) inconsistent position

### ISSUE THREAD

**Issue by marcellogalhardo** [whitescent/Mastify#104]
Home and Explore shows the menu drawer button (photo) on the right side. Notification shows on the left side. It would be great if they match.

I would recommend to keep the menu drawer button on the left side consistently for all tabs.

![Screenshot_20240329-011935.png](https://github.com/whitescent/Mastify/assets/4348197/50f115d9-f423-4357-991e-f13bc71104a1)

![Screenshot_20240329-012112.png](https://github.com/whitescent/Mastify/assets/4348197/ac97eb63-7d0c-41db-af14-39bb37711c59)

**Comment by whitescent** [comment]
fixed https://github.com/whitescent/Mastify/commit/4a2b288e0baa2582547242a3f25bce1a8a9253e2

It will be fixed in the next version (1.4.25-alpha)
