### ISSUE TITLE
Home New Post Icon Wrong Position on OnePlus Ace3

### ISSUE THREAD

**Issue by galiren** [whitescent/Mastify#115]
I am debugging Mastify on my physical device OnePlus Ace 3 and found the New Post Icon was partially hiden by BottomBar like below:
<img src="https://github.com/user-attachments/assets/be3251ec-05b4-4ce8-b696-d58b4be49d84" width="200"/>
This is not observed on Android Studio virtual device (Pixel 8 Pro).

Although increasing image vertical padding may lift the image a litte bit and "fix" this situation, but I am seeking more hleps to find if we can get a better solution comforming all devices.

Thank you in advance for any possible suggestions and investigations.

**Comment by whitescent** [comment]
#116 This PR should fix the issue. You can try running it again with the latest main branch to see if the problem persists.

In fact, there are many places in Mastify's current code that are poorly written :((. I'm trying to rewrite it using a multi-module structure.

As for the solution to this issue, the `innerPadding` provided by `Scaffold` can actually resolve it, as it measures the height of the BottomBar @Composable. Therefore, you just need to add padding(bottom = innerPadding.calculateBottomPadding()) to the Home Screen. But I don't know why i forgot to use it before.

`Scaffold.kt`
```kotlin
val bodyContentPlaceables = subcompose(ScaffoldLayoutContent.MainContent) {
    val insets = contentWindowInsets.asPaddingValues(this@SubcomposeLayout)
    val innerPadding = PaddingValues(
        top =
        if (topBarPlaceables.isEmpty()) {
            insets.calculateTopPadding()
        } else {
            topBarHeight.toDp()
        },
        bottom =
        if (bottomBarPlaceables.isEmpty() || bottomBarHeight == null) {
            insets.calculateBottomPadding()
        } else {
            bottomBarHeight.toDp()
        },
        start = insets.calculateStartPadding((this@SubcomposeLayout).layoutDirection),
        end = insets.calculateEndPadding((this@SubcomposeLayout).layoutDirection)
    )
    content(innerPadding)
}.fastMap { it.measure(looseConstraints) }
```
