### ISSUE TITLE
[Intent to implement] Share

### ISSUE THREAD

**Issue by lazzzis** [whitescent/Mastify#19]
(Raise an issue as suggested in the README)

Hi, I'd like to implement the share feature on Mastify. See screen record.

I plan to introduce a ShareButton to replace the two buttons on StatusListItem and StatusDetailCard, like following

```kotlin
ClickableIcon(
  painter = painterResource(id = R.drawable.share_network),
  modifier = Modifier.size(statusDetailActionsIconSize),
  tint = AppTheme.colors.primaryContent,
  onClick = {
    val sendIntent: Intent = Intent(Intent.ACTION_SEND).apply {
      putExtra(Intent.EXTRA_TEXT, statusUiData.link)
      type = "text/html"
    }

    val shareIntent = Intent.createChooser(sendIntent, null)
    startActivity(context, shareIntent, null)
  }
)
```

Let me know if this looks good to you. If so, I will create a pull request in next few days.

https://github.com/whitescent/Mastify/assets/10359255/93c49687-cd55-484e-9c7b-23377b96a90c

**Comment by whitescent** [comment]
yes, LGTM !
