### ISSUE TITLE
[Intent to implement] Navigate to profile screen if the opened link navigates to a user's profile

### ISSUE THREAD

**Issue by lazzzis** [whitescent/Mastify#20]
Currently, clicking on the mentioned names will open a chrome custom tab. Ideally, it should navigate to the user's profile page. See screen record.

I plan to expose Status.Mention to StatusUiData. In the StatusDetailCard and StatusContent, if the clicked link matches a url in the `mention` list, it should navigate the user to the profile instead, like following:

```kotlin
onLinkClick = { span ->
  val mention = statusUiData.mentions.firstOrNull { it.url == span }
  if (mention != null) {
    navigateToProfile(mention.toAccount())
  } else {
    launchCustomChromeTab(
      context = context,
      uri = Uri.parse(span),
      toolbarColor = primaryColor.toArgb(),
    )
  }
},
```

The `mention.toAccount` will convert the mention to an Account entity whose id is from `mention`. IIUC, the fetchAccount will fetch the up-to-date user profile using the id when initialized.

Let me know if this looks good to you.

https://github.com/whitescent/Mastify/assets/10359255/44f34a8e-17ef-4e42-a4ed-39592ede275d

**Comment by whitescent** [comment]
yes, this should be a deep links, probably not limited to accounts, but also similar tags (e.g #topc), statuses, It may be necessary to create a new screen for #tags, but I haven't designed it yet.

but anyway, you can create a PR to implementation account navigation ! ❤️
