### ISSUE TITLE
[Intent to implement] Dynamic corner radius of ReplyTextField

### ISSUE THREAD

**Issue by lazzzis** [whitescent/Mastify#34]
Currently, the corner radius of ReplyTextField is fixed to 0. The border is truncated by the round corner on my device.

<img width="529" alt="Screenshot 2024-02-06 at 11 02 29 AM" src="https://github.com/whitescent/Mastify/assets/10359255/f7ece020-5eaf-499c-be1f-70f79bb9040f">

This is also observed in multi-window mode.

<img width="529" alt="Screenshot 2024-02-06 at 11 02 29 AM" src="https://github.com/whitescent/Mastify/assets/10359255/bd5a1c9e-60b4-4887-9899-6563d60a8cd3">

**Question**: In terms of UX considerations, does an implementation of a dynamic corner radius make sense to you? i.e.: the radius equals to the screen's corner radius if the ReplyTextField at the bottom of the window; otherwise, it stays 0.

---
Tech details:
By making use of [RoundedCorner API](https://developer.android.com/reference/android/view/RoundedCorner) and [WindowManager#getCurrentWindowMetrics API](https://developer.android.com/reference/android/view/WindowManager#getCurrentWindowMetrics()), the code may look like this 

```kotlin
// ReplyTextField.kt
// Not actual code

val cornerRadius = rootWindowInsets.getRoundedCorner(RoundedCorner.POSITION_BOTTOM_LEFT).radius
var bottomRadius by remember { mutableStateOf(0.dp) }

  Surface(
    modifier = modifier
      .onGloballyPositioned {
        if (it.boundsInWindow().bottom == currentWindowSize.bounds.bottom) {
          bottomRadius = cornerRadius
        } else {
          bottomRadius = 0.dp
        }
      },
// ...
 shape = RoundedCornerShape(
      // ...
      bottomStart = bottomRadius,
      bottomEnd = bottomRadius

```

**Comment by whitescent** [comment]
sounds like a good idea, this should make it better compatible with other devices ! ❤️
