### ISSUE TITLE
Show emojis in the spoiler text?

### ISSUE THREAD

**Issue by lazzzis** [whitescent/Mastify#35]
![spoiler-text-before](https://github.com/whitescent/Mastify/assets/10359255/e986c028-61c7-4b79-a589-7179109f8578)

Wondering if you have any concern to use `statusUiData.content.ifEmpty` here and a `HtmlText` in SensitiveBar.kt?

https://github.com/whitescent/Mastify/blob/49189e74133f10fe3ea5a054df87b21244e3c0e8/app/src/main/java/com/github/whitescent/mastify/ui/component/status/StatusListItem.kt#L325

**Comment by whitescent** [comment]
no, i forgot to use text with emoji here, just fixed it
