### ISSUE TITLE
Splash screen shows a generic Android icon

### ISSUE THREAD

**Issue by Porkepix** [whitescent/Mastify#42]
See joined screenshot, when starting the application, the splashscreen displays a generic Android icon.

<details>
<summary>
Screenshot
</summary>

![Screenshot_20240210-075723](https://github.com/whitescent/Mastify/assets/709500/938d0931-d0f0-481f-acfd-966b9330f0fc)

</details>

Device runs Android Oreo (8.0) stock ROM.

**Comment by whitescent** [comment]
Fixed and will be released in the next version
