### ISSUE TITLE
[Good First Issue] Timestamp format

### ISSUE THREAD

**Issue by whitescent** [whitescent/Mastify#50]
The time format for the post detail page is now YY/MM/DD HH:MM, but in general, we don't need to show the year.

However, there is no good way to display only MM/DD HH:MM yet, because this time format must be localized according to the language
I tried using regex a long time ago, but there may be some regions where the language is still having issues.

```kotlin
val timestamp: Long = ZonedDateTime.now().toEpochSecond()

insert(timestamp) // inserted into the database, can be ignored

val timestamp: ZonedDateTime = ZonedDateTime.ofInstant(
  Instant.ofEpochSecond(DataBase.timestamp), 
  ZoneId.systemDefault()
)

val date = timestamp.toLocalDate().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.MEDIUM))

// The output is based on the year, month and day of all localizations
// for example
// 8 Aug, 2021 // English, United Kingdom
// Aug 8, 2021 // English, United States
// 8/19/2021
// 2021/8/19
// 2021年8月19日

val time = timestamp.toLocalTime().format(DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT))


// retrieving localized date string without year
val timestamp: ZonedDateTime = ZonedDateTime.ofInstant(
  Instant.ofEpochSecond(puzzle.timestamp), 
  ZoneId.systemDefault()
)
lateinit var monthDay: String

val pattern = DateTimeFormatterBuilder.getLocalizedDateTimePattern(FormatStyle.FULL, null, IsoChronology.INSTANCE, Locale.getDefault())
val dayRange = "d+[^,./-]?".toRegex().find(pattern)!!.range
val monthRange = "[ML]+[^,./-]?".toRegex().find(pattern)!!.range
val startIdx = min(dayRange.first, monthRange.first)
val endIdx = max(dayRange.last, monthRange.last)
val remaining = pattern.substring(startIdx, endIdx + 1)

monthDay = timestamp.format(DateTimeFormatter.ofPattern(remaining))

// Aug 8
// 8 Aug
// 8月19日
```

The handling of this timestamp is in this [file](https://github.com/whitescent/Mastify/blob/main/app/src/main/java/com/github/whitescent/mastify/utils/FormatFactory.kt#L37-L39),  so if anyone wants to fix it, feel free to send a Pull Request!

**Comment by theSC0RP** [comment]
Hey @whitescent, can I give this a try?

**Comment by whitescent** [comment]
Yes, sure!

**Comment by lazzzis** [comment]
Is it ok to bump min OS to N such that we can use [android.icu.text.DateFormat](https://developer.android.com/reference/kotlin/android/icu/text/DateFormat#)?

```kotlin
      val formatter =
        android.icu.text.DateFormat.getPatternInstance(
          android.icu.text.DateFormat.ABBR_MONTH_DAY,
          Locale.getDefault(),
        )
      formatter.format(Date.from(timestamp.toInstant().toJavaInstant()))
```

Output:
Simplified Chinese:
<img width="264" alt="Screenshot 2024-02-17 at 12 52 38 PM" src="https://github.com/whitescent/Mastify/assets/10359255/2c61cc37-7d27-4361-ba90-82d20fec289e">

English (US):

<img width="267" alt="Screenshot 2024-02-17 at 12 51 19 PM" src="https://github.com/whitescent/Mastify/assets/10359255/d5386c61-a89c-4387-a662-50b38b82f0bf">

English (UK):
<img width="267" alt="Screenshot 2024-02-17 at 12 54 02 PM" src="https://github.com/whitescent/Mastify/assets/10359255/69b3805e-721b-4c81-9176-ce08f2773ec0">

**Comment by whitescent** [comment]
@lazzzis LGTM ! Can you submit a PR? 
Should judge the year tho, if it's not this year then show the year
