### ISSUE TITLE
Can't use settings

### ISSUE THREAD

**Issue by DerpDerpingtonIsHere** [whitescent/Mastify#77]
This app does not allow me to enter settings. I click the cog wheel on top next to the profile picture which does nothing. I also click my user profile, click settings in there as well which also does nothing. 

Versions: 1.4.0-alpha and 1.4.2-alpha

Android version: 12

If any other information is needed I can try my best to provide it.

**Comment by lazzzis** [comment]
I think the settings feature is not implemented by the author yet. See the timeline of the README.

https://github.com/whitescent/Mastify/blob/0056f45d8c8c0b05d2c23ddfd4f2023c9a5a3047/.github/README.md?plain=1#L59

**Comment by whitescent** [comment]
yes, the settings feature not implemented yet, check [roadmap](https://github.com/whitescent/Mastify?tab=readme-ov-file#roadmap)
