### ISSUE TITLE
Notifications: empty content and navigating to profile

### ISSUE THREAD

**Issue by lazzzis** [whitescent/Mastify#80]
This notification is showing an empty box:

<img width="402" alt="Screenshot 2024-02-27 at 10 14 44 PM" src="https://github.com/whitescent/Mastify/assets/10359255/fb68d57d-d0df-4134-a696-4a67238e3641">

Original post is a reply with an attachment:

<img width="406" alt="Screenshot 2024-02-27 at 10 14 53 PM" src="https://github.com/whitescent/Mastify/assets/10359255/5da4de52-9429-41b2-883c-43b412872023">

1. do we need to show an empty box in this case? i.e; remove the box and show the picture only
2. currently, clicking on the attachment picture navigates user to the profile rather than the status detail. Is this intentional?

Does this proposal sound good to you: clicking on BasicEvent navigates user to StatusDetail screen while clicking on FollowEvent navigates to Profile screen?

**Comment by whitescent** [comment]
1. NO, just show the pictures
2. this is not the expected behavior, maybe navigate to the post details page

>clicking on BasicEvent navigates user to StatusDetail screen while clicking on FollowEvent navigates to Profile screen

yes, but if the user's avatar is clicked on the BasicEvent, it still needs to navigate to the Profile page
